
name: Check code quality and run unit tests

on: [push]

jobs:
  prepare:
    if: ${{ github.ref }} != 'refs/heads/${{ github.event.repository.default_branch }}'
    runs-on: ubuntu-latest
    steps:
    - uses: mahdilamb/check-python-package@main
      with: 
        use_version_check: true
        version_check_path: takeout_maps/__init__.py
        use_black: true
        black_args: '"takeout_maps" "tests"'
        use_isort: true
        isort_args: '"takeout_maps" "tests"'

  build:
    needs: prepare

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: browser-actions/setup-chrome@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Print dependencies
        run: pip freeze
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Unit tests [pytest]
        if: ${{ always() }}
        env: # Or as an environment variable
          FITBIT_CLIENT_ID: ${{ secrets.FITBIT_CLIENT_ID }}
          FITBIT_CLIENT_SECRET: ${{ secrets.FITBIT_CLIENT_SECRET }}
          FITBIT_REDIRECT_URL: ${{ secrets.FITBIT_REDIRECT_URL }}
        
        run: pytest --cov=takeout_maps --cov-report term-missing
      - name: Check docstrings [pydocstyle]
        if: ${{ always() }}
        run: pydocstyle takeout_maps
      - name: Check code quality [black]
        if: ${{ always() }}
        run: black --check takeout_maps
      - name: Check security [bandit]
        if: ${{ always() }}
        run: bandit -r takeout_maps
